version: '3.4'

networks:
  ct:

services:
  server.node:
    image: server.node
    build: .
    networks:
      - ct
    environment:
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    depends_on:
      - db
    restart: always
    ports:
      - 4000:4000
      - 9330:9330
    command: ["npm", "--inspect=0.0.0.0:9330", "start"]
  db:
    image: mysql:8.0.11
    networks:
      - ct
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE