version: '3.4'

networks:
  ct:

services:
  server.node:
    container_name: ct_server
    image: server.node
    build: .
    networks:
      - ct
    environment:
      - DATABASE_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - WAIT_HOSTS
      - WAIT_HOSTS_TIMEOUT
      - WAIT_SLEEP_INTERVAL
      - WAIT_HOST_CONNECT_TIMEOUT
      - GRAPHQL_ENDPOINT_PORT
      - AUTH_AAD_CHERRYTWIST_API_APP_ID
      - AUTH_AAD_LOGGING_PII
      - AUTH_AAD_LOGGING_LEVEL
      - AUTH_AAD_MSGRAPH_API_SECRET
      - AUTH_AAD_MSGRAPH_API_SCOPE
      - AUTH_AAD_UPN_DOMAIN
      - AUTH_AAD_TENANT
      - AUTH_ENABLED
    depends_on:
      - db
    restart: always
    ports:
      - 4000:4000
    command: sh -c "/wait && npm start"
  db:
    container_name: ct_server_db
    image: mysql:8.0.11
    networks:
      - ct
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE

