kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: ct-server-deployment
  labels:
    app: ct-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-server
  template:
    metadata:
      labels:
        app: ct-server
    spec:
      containers:
        - name: ct-server
          image: ctdev.azurecr.io/ct-server:latest
          env:
          - name: secrets
            valueFrom:
              secretKeyRef:
                name: ct-secrets
                key: .env.secrets
          - name: api
            valueFrom:
              configMapKeyRef:
                name: ct-config
                key: .env.auth.api
          - name: client
            valueFrom:
              configMapKeyRef:
                name: ct-config
                key: .env.auth.client
          - name: common
            valueFrom:
              configMapKeyRef:
                name: ct-config
                key: .env.auth.common
          - name: logging
            valueFrom:
              configMapKeyRef:
                name: ct-config
                key: .env.logging
          - name: mysql
            valueFrom:
              configMapKeyRef:
                name: ct-config
                key: .env.mysql
          - name: waithosts
            valueFrom:
              configMapKeyRef:
                name: ct-config
                key: .env.wait.hosts
          - name: elasticCloud
            valueFrom:
              configMapKeyRef:
                name: ct-config
                key: .env.elastic.cloud
          ports:
            - name: graphql
              containerPort: 4000
