kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: ct-server-deployment
  labels:
    app: ct-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ct-server
  template:
    metadata:
      labels:
        app: ct-server
    spec:
      containers:
        - name: ct-server
          image: ctdev.azurecr.io/ct-server:latest
          env:
          - name: "SECRETS"
            valueFrom:
              secretKeyRef:
                name: ct-secrets
                key: .env.secrets
          - name: "API"
            valueFrom:
              secretKeyRef:
                name: ct-config
                key: .env.auth.api
          - name: "CLIENT"
            valueFrom:
              secretKeyRef:
                name: ct-config
                key: .env.auth.client
          - name: "common"
            valueFrom:
              secretKeyRef:
                name: ct-config
                key: .env.auth.common
          - name: "logging"
            valueFrom:
              secretKeyRef:
                name: ct-config
                key: .env.logging
          - name: "mysql"
            valueFrom:
              secretKeyRef:
                name: ct-config
                key: .env.mysql
          - name: "waithosts"
            valueFrom:
              secretKeyRef:
                name: ct-config
                key: .env.wait.hosts
          ports:
            - name: graphql
              containerPort: 4000
