name: Build & Deploy to Test on Azure

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:${{ github.sha }}

      - uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CRED_K8S_NEW }}
          cluster-name: k8s-test
          resource-group: res-grp-k8s-test

      - uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: alkemio-server-secret

      - uses: azure/setup-kubectl@v3
        with:
          version: "v1.22.0" # default is latest stable, fixing it to a compatible version
        id: install

      - name: Migrate database
        run: |
          kubectl delete job alkemio-server-migration
          kubectl create job --from=cronjob/alkemio-server-migration alkemio-server-migration-job

      - uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/25-server-deployment-dev.yaml
            manifests/30-server-service.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-server:${{ github.sha }}
          imagepullsecrets: |
            alkemio-server-secret
